/**
 * Generates src/lib/abis.ts from Foundry's build output.
 *
 * Hand-written frontend ABIs drift from the contracts silently — you only find out when a call
 * reverts with no useful message. `contracts/out` is gitignored (build output), so the generated
 * file is committed instead, same arrangement as contracts/src/JudgesGroth16Verifier.sol.
 *
 * Run after changing any contract signature:
 *   cd contracts && forge build
 *   pnpm --filter @judges/web run abis:export
 */
import path from "node:path";
import { readFileSync, writeFileSync } from "node:fs";

const OUT_DIR = path.join(import.meta.dirname, "..", "..", "..", "contracts", "out");
const TARGET = path.join(import.meta.dirname, "..", "src", "lib", "abis.ts");

/** Only the functions/events the frontend actually needs — a full ABI dump would be noise. */
const CONTRACTS = [
  { file: "SybilResistantDAO.sol", name: "SybilResistantDAO", exportName: "daoAbi" },
  { file: "AgentRegistry.sol", name: "AgentRegistry", exportName: "agentRegistryAbi" },
  { file: "SybilResistantFaucet.sol", name: "SybilResistantFaucet", exportName: "faucetAbi" },
  { file: "JudgesVerifier.sol", name: "JudgesVerifier", exportName: "judgesVerifierAbi" },
];

function loadAbi(file: string, name: string): unknown[] {
  const artifactPath = path.join(OUT_DIR, file, `${name}.json`);
  try {
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
    if (!Array.isArray(artifact.abi)) throw new Error("artifact has no abi array");
    return artifact.abi;
  } catch (err) {
    throw new Error(
      `Could not read ${artifactPath}. Run \`forge build\` in contracts/ first. (${
        err instanceof Error ? err.message : String(err)
      })`,
    );
  }
}

const blocks = CONTRACTS.map(({ file, name, exportName }) => {
  const abi = loadAbi(file, name);
  return `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`;
});

const contents = `// AUTO-GENERATED by scripts/export-abis.ts from Foundry build output -- do not hand-edit.
// Regenerate after any contract signature change:
//   cd contracts && forge build && cd ../apps/web && pnpm run abis:export

${blocks.join("\n\n")}
`;

writeFileSync(TARGET, contents);
console.log(`Wrote ${TARGET} (${CONTRACTS.length} ABIs)`);
