// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture_v2.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership_v2.circom or the v2 trusted setup
// (prover/build/judges_membership_v2_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";
import {CommitmentTree} from "../src/CommitmentTree.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;
    CommitmentTree commitmentTree;

    // A real Groth16 membership proof (judges_membership_v2), generated by
    // prover/scripts/export_verifier_fixture_v2.ts. The proof is bound to WALLET via CONTEXT_HASH
    // and to the published MERKLE_ROOT.
    uint256[2] pA = [uint256(0x305db863907750cdbf9a9446ea706249757260bf8b67757ac3987255933ee283), uint256(0x19765a13af439faae4cf8f804199e9e2e86edfb83e049c871daca0783761791b)];
    uint256[2][2] pB = [[uint256(0x0d7959c19c613ed7e382d340c73495633b2cf279de3d12c7340fcee622ec9b25), uint256(0x009bb83abe382e7228f6a91e04b708f1986a610af5a199bcb329bf8b9cd015b0)], [uint256(0x1186a6c83b7a1b2a4c041e448166259dd9116eaa4941353248fc10522f221470), uint256(0x27d73d1698a8fcb372a565f33c5a115ba47a001ba8180c777f500299c89008d7)]];
    uint256[2] pC = [uint256(0x142550f4bd7a0b6e558a01662e4cabba7039e751ce98f332974a68d60f61d502), uint256(0x224ffc24aa19abf8dc04c9c0e7a0ecf2190f3685c570664b68e611d4594e60ca)];

    bytes32 constant MERKLE_ROOT = bytes32(uint256(11937388175268477019568674142528069784036990133803166367643534548541439449801));
    bytes32 constant NULLIFIER = bytes32(uint256(7625446735103236322057525028743989179283721503007158249661141328252094923462));
    bytes32 constant DOMAIN = bytes32(uint256(547563673512369728355808114945278138262070984877501223412563527389581952200));
    bytes32 constant CONTEXT_HASH = 0xd42cf291b72edcbdfd45102cc2d12d960a166f6a6b2352b09e885e4660d450d5;
    bytes32 constant EXPECTED_POLICY_HASH = bytes32(uint256(16946833076561846871962365099292301638095694619658226523360659375813657004663));
    // Emitted as a uint160 cast, not a hex literal: solc rejects non-EIP-55-checksummed address
    // literals, and generating a checksummed string here would just be another thing to get
    // subtly wrong.
    address constant WALLET = address(uint160(48879));

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        commitmentTree = new CommitmentTree();
        judgesVerifier =
            new JudgesVerifier(address(zkVerifier), address(nullifierRegistry), address(commitmentTree));
        nullifierRegistry.setVerifier(address(judgesVerifier));
        // Publish the root the proof was generated against; this test contract is the deployer.
        commitmentTree.setRootPoster(address(this));
        commitmentTree.postRoot(MERKLE_ROOT);
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    /// @dev The cross-language check: Solidity's policyHashFor must equal what TS's
    ///      derivePolicyHash produced when the proof was generated.
    function test_PolicyHashMatchesOffchainDerivation() public view {
        assertEq(judgesVerifier.policyHashFor(CONTEXT_HASH, WALLET), EXPECTED_POLICY_HASH);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The membership check: a root the tree never published is rejected before proof verification.
    function test_UnpublishedRootRejected() public {
        bytes32 unknownRoot = bytes32(uint256(MERKLE_ROOT) ^ 1);
        vm.expectRevert(JudgesVerifier.UnknownRoot.selector);
        judgesVerifier.verify(_proofBytes(), unknownRoot, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The wallet binding: someone lifting this proof and submitting it for their own address gets nothing.
    function test_ProofStolenForADifferentWalletRejected() public {
        address attacker = address(0xA11CE);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, attacker);
    }

    /// @dev The action binding: the same proof can't be redirected to a different action.
    function test_ProofRedirectedToDifferentActionRejected() public {
        bytes32 otherContext = bytes32(uint256(CONTEXT_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, otherContext, WALLET);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, wrongDomain, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }
}
