// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership.circom or the trusted setup
// (prover/build/judges_membership_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;

    // A real Groth16 proof for a real membership witness, generated by
    // prover/scripts/export_verifier_fixture.ts -- see that script for how the underlying
    // credentialSecret/commitment/nullifier were derived. The proof is bound to WALLET via
    // CONTEXT_HASH, so it only verifies for that exact wallet+action pair.
    uint256[2] pA = [uint256(0x09f7a2b5b699bb93ed349ae7fe32acaffc7721453a5d6f79d6ca27bd3020883a), uint256(0x1ab57deef53374de192708f2cd819cae89bb0f0018d0dfb9c98a066893141fbd)];
    uint256[2][2] pB = [[uint256(0x18ae7af79d5fb5e4b8605e0b9d3059907ddf533824b297df7179f87dfc3024b3), uint256(0x0fb05ecc362a266238950ef9aa65cf977c74d852d689c8921794c5422db43359)], [uint256(0x2e6a39ea2e443b84858c49cfb64a97138f9b388001c333d38eeb52cf48121d02), uint256(0x27c3999c43f568fb1943d0f741726f75be2a7de2fdd759d63448bdb0c7411077)]];
    uint256[2] pC = [uint256(0x175d324173ad572d27e1655160302365884df81cdc24b38082fb2723c173826a), uint256(0x0a63da1c1d05599015e1b17b2baa5e7bade2e4894762ad7924f111fbe06da925)];

    bytes32 constant WALLET_COMMITMENT = bytes32(uint256(7092197767953043405674336534699365876909175202055686886337654301675053137900));
    bytes32 constant NULLIFIER = bytes32(uint256(8464374668426453352188664848870033382158765054915873869183892323245329383940));
    bytes32 constant DOMAIN = bytes32(uint256(547563673512369728355808114945278138262070984877501223412563527389581952200));
    bytes32 constant CONTEXT_HASH = 0xd42cf291b72edcbdfd45102cc2d12d960a166f6a6b2352b09e885e4660d450d5;
    bytes32 constant EXPECTED_POLICY_HASH = bytes32(uint256(16946833076561846871962365099292301638095694619658226523360659375813657004663));
    // Emitted as a uint160 cast, not a hex literal: solc rejects non-EIP-55-checksummed address
    // literals, and generating a checksummed string here would just be another thing to get
    // subtly wrong.
    address constant WALLET = address(uint160(48879));

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        judgesVerifier = new JudgesVerifier(address(zkVerifier), address(nullifierRegistry));
        nullifierRegistry.setVerifier(address(judgesVerifier));
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    /// @dev The cross-language check: Solidity's policyHashFor must equal what TS's
    ///      derivePolicyHash produced when the proof was generated. If these ever diverge,
    ///      every proof silently stops verifying on-chain.
    function test_PolicyHashMatchesOffchainDerivation() public view {
        assertEq(judgesVerifier.policyHashFor(CONTEXT_HASH, WALLET), EXPECTED_POLICY_HASH);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The whole point of the wallet binding: someone lifting this proof out of the mempool
    ///      and submitting it for their own address gets nothing.
    function test_ProofStolenForADifferentWalletRejected() public {
        address attacker = address(0xA11CE);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, attacker);
    }

    /// @dev And the action binding: the same proof can't be redirected to a different action.
    function test_ProofRedirectedToDifferentActionRejected() public {
        bytes32 otherContext = bytes32(uint256(CONTEXT_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, otherContext, WALLET);
    }

    function test_TamperedWalletCommitmentRejected() public {
        bytes32 wrongCommitment = bytes32(uint256(WALLET_COMMITMENT) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), wrongCommitment, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, wrongDomain, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }
}
