// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership.circom or the trusted setup
// (prover/build/judges_membership_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;

    // A real Groth16 proof for a real membership witness, generated by
    // prover/scripts/export_verifier_fixture.ts -- see that script for how the underlying
    // credentialSecret/commitment/nullifier were derived.
    uint256[2] pA = [uint256(0x2a2090290d863405994d3245c1421ee315cd5d62a07d83736d6b4971eb9f3bac), uint256(0x1eec1f62134e473404c2b7b6006077192767577386486a2ab20e1d8919fca69f)];
    uint256[2][2] pB = [[uint256(0x18c93c70b8ce650cd50eb64a5aa1822d0564b7e3e4d70fb6fe2119d236fdf8a1), uint256(0x2764a2b65e978f61d2bb76606b2fbc5529f7fa2a8e2fa12bd4c01d50a3403f39)], [uint256(0x22a4f9558b889a8ee10abc8ef3d2789788d4a825a2b80d84384ba69fa7eec63a), uint256(0x2e50aab2648e7bdcb81c67e8a1d2b303d8541109ae03afd0dcae065f6e8bf46b)]];
    uint256[2] pC = [uint256(0x08a6976b963707c19b76cb20273b6ac6eed397fb6e1a992467222f7382570e11), uint256(0x20f841324d2290fc4a52078fa1733b8de6945d6e4f15bb158a41f16fe688dfca)];

    bytes32 constant WALLET_COMMITMENT = bytes32(uint256(7092197767953043405674336534699365876909175202055686886337654301675053137900));
    bytes32 constant NULLIFIER = bytes32(uint256(8464374668426453352188664848870033382158765054915873869183892323245329383940));
    bytes32 constant DOMAIN = bytes32(uint256(547563673512369728355808114945278138262070984877501223412563527389581952200));
    bytes32 constant POLICY_HASH = bytes32(uint256(7));

    address wallet = address(0xBEEF);

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        judgesVerifier = new JudgesVerifier(address(zkVerifier), address(nullifierRegistry));
        nullifierRegistry.setVerifier(address(judgesVerifier));
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_TamperedWalletCommitmentRejected() public {
        bytes32 wrongCommitment = bytes32(uint256(WALLET_COMMITMENT) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), wrongCommitment, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_TamperedPolicyHashRejected() public {
        bytes32 wrongPolicy = bytes32(uint256(POLICY_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, wrongPolicy, wallet);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, wrongDomain, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }
}
