// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_domain_fixture.ts -- do not hand-edit.
// Re-run that script if packages/crypto's field/policy derivation ever changes.

import {Test} from "forge-std/Test.sol";
import {JudgesField} from "../src/libraries/JudgesField.sol";

/// @notice Pins Solidity's JudgesField against values computed by packages/crypto.
/// @dev These are the two halves of every proof: the prover reduces the app id and the
///      wallet/action binding into BN254's scalar field in TypeScript, and the contracts redo it
///      in Solidity. If they disagree, proofs simply stop verifying on-chain and nothing points
///      at the hash function -- so the agreement is pinned here rather than discovered at deploy
///      time.
contract JudgesFieldTest is Test {
    function test_HashToFieldMatchesOffchain() public pure {
        assertEq(JudgesField.hashToField("judges-dao"), 10994257461746157991108903974129773447139490240507076374014457240489892760041, "judges-dao");
        assertEq(JudgesField.hashToField("judges-agent-registry"), 9244310085629582425320946190870823193255377731412033823331977374644154742906, "judges-agent-registry");
        assertEq(JudgesField.hashToField("judges-faucet"), 3773263380300163156480110639666283676197854324004723799255264790321018509916, "judges-faucet");
        assertEq(JudgesField.hashToField("judges-demo"), 547563673512369728355808114945278138262070984877501223412563527389581952200, "judges-demo");
    }

    function test_PolicyHashMatchesOffchain() public pure {
        // case 0: assurance "user_verified"
        assertEq(
            JudgesField.policyHash(0xd42cf291b72edcbdfd45102cc2d12d960a166f6a6b2352b09e885e4660d450d5, address(uint160(48879))),
            16946833076561846871962365099292301638095694619658226523360659375813657004663,
            "user_verified"
        );
        // case 1: assurance "possession"
        assertEq(
            JudgesField.policyHash(0x8b616aa60af2d3584e4a55ce68e6bbca718dbaf025e6fbdb2dcda0a910b9259f, address(uint160(97433442488726861213578988847752201310395502865))),
            4669376955280137234999061027013171604837455727868224522708685355078247536538,
            "possession"
        );
    }

    function test_FieldPrimeMatchesBn254ScalarField() public pure {
        assertEq(
            JudgesField.FIELD_PRIME,
            21888242871839275222246405745257275088548364400416034343698204186575808495617
        );
    }
}
