// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_webauthn_spike_fixture.ts -- do not hand-edit.

import {Test, console} from "forge-std/Test.sol";
import {WebAuthnOnchainSpike} from "../experiments/WebAuthnOnchainSpike.sol";

/// @notice Measures what on-chain WebAuthn verification would cost, using a real assertion.
/// @dev Monad's P256VERIFY precompile doesn't exist in Foundry's local EVM (the Phase 3
///      finding), so 0x100 is mocked here to return 1. That means the measured number covers
///      EVERYTHING EXCEPT the precompile itself: calldata, the rpIdHash/flag checks, base64url
///      encoding the challenge, the two sha256 calls, and the string comparisons. Monad's
///      documented 6,900 gas for P256VERIFY is added on top when reporting.
contract WebAuthnOnchainSpikeTest is Test {
    WebAuthnOnchainSpike spike;

    bytes constant AUTHENTICATOR_DATA = hex"8ed7cf113da3ca0d52a66104463bd0399d270733a92680b979f25e6c363faa43050000002a";
    bytes constant CLIENT_DATA_JSON = hex"7b2274797065223a22776562617574686e2e676574222c226368616c6c656e6765223a22564477484376756a69556677306e38397372386a746346744a5335445137586e485366316a433668483359222c226f726967696e223a2268747470733a2f2f6a75646765732e76657263656c2e617070222c2263726f73734f726967696e223a66616c73657d";
    uint256 constant TYPE_INDEX = 1;
    uint256 constant CHALLENGE_INDEX = 23;
    bytes32 constant EXPECTED_RP_ID_HASH = 0x8ed7cf113da3ca0d52a66104463bd0399d270733a92680b979f25e6c363faa43;
    bytes32 constant EXPECTED_CHALLENGE = 0x543c070afba38947f0d27f3db2bf23b5c16d252e4343b5e71d27f58c2ea11f76;
    bytes32 constant R = 0x697f422b3ab9893bdbb593e9ff146b54f971c795d8d7a43c12a18a11d9e710e5;
    bytes32 constant S = 0x8c9ce0b6ac2a537996d121cd471bd8460b002cc7497247518876238997cdc064;
    bytes32 constant QX = 0x42167dd2df57565a4fc4bb6c5cbd47106f80d3ff46995f321661724da1e9003e;
    bytes32 constant QY = 0x6675481e21918b1a531254e762f2f7305207a504100fe1a6cc6a6148e1f1a8ab;

    /// @dev Documented Monad cost, from https://docs.monad.xyz/developer-essentials/precompiles
    uint256 constant MONAD_P256VERIFY_GAS = 6_900;

    function setUp() public {
        spike = new WebAuthnOnchainSpike();
        // Mock P256VERIFY: returns 32 bytes of 1, like the real precompile does for a valid
        // signature. Costs ~a few hundred gas instead of the real 6,900, which is corrected for
        // in the reported totals.
        // PUSH1 1, PUSH1 0, MSTORE, PUSH1 0x20, PUSH1 0, RETURN -- returns 32 bytes of value 1.
        vm.etch(address(0x100), hex"600160005260206000f3");
    }

    function _assertion() internal pure returns (WebAuthnOnchainSpike.Assertion memory) {
        return WebAuthnOnchainSpike.Assertion({
            authenticatorData: AUTHENTICATOR_DATA,
            clientDataJSON: CLIENT_DATA_JSON,
            typeIndex: TYPE_INDEX,
            challengeIndex: CHALLENGE_INDEX,
            r: R,
            s: S,
            qx: QX,
            qy: QY
        });
    }

    function _call() internal view returns (bool) {
        return spike.verifyAssertion(_assertion(), EXPECTED_RP_ID_HASH, EXPECTED_CHALLENGE);
    }

    function test_AssertionVerifies() public view {
        assertTrue(_call(), "real assertion should verify with a passing precompile mock");
    }

    function test_WrongChallengeRejected() public view {
        bool ok =
            spike.verifyAssertion(_assertion(), EXPECTED_RP_ID_HASH, bytes32(uint256(EXPECTED_CHALLENGE) ^ 1));
        assertFalse(ok, "an assertion for a different challenge must not verify");
    }

    function test_WrongRpIdRejected() public view {
        bool ok =
            spike.verifyAssertion(_assertion(), bytes32(uint256(EXPECTED_RP_ID_HASH) ^ 1), EXPECTED_CHALLENGE);
        assertFalse(ok, "an assertion for another relying party must not verify");
    }

    function test_MeasureGas() public view {
        uint256 before = gasleft();
        bool ok = _call();
        uint256 used = before - gasleft();
        assertTrue(ok);

        console.log("--- on-chain WebAuthn verification, measured ---");
        console.log("authenticatorData bytes", AUTHENTICATOR_DATA.length);
        console.log("clientDataJSON bytes   ", CLIENT_DATA_JSON.length);
        console.log("EVM execution (precompile mocked, excl. tx calldata)", used);
        console.log("plus real P256VERIFY on Monad", MONAD_P256VERIFY_GAS);
        console.log("subtotal", used + MONAD_P256VERIFY_GAS);
    }
}
