/**
 * Generates a real Groth16 proof against a real membership witness, then emits a Foundry test
 * file exercising the deployed JudgesGroth16Verifier + JudgesVerifier with it directly -- no
 * manual transcription of proof/public-signal values (same reasoning as the P256 test vector in
 * contracts/test/MonadP256Adapter.t.sol: hand-copying long hex/decimal numbers is exactly the
 * kind of thing that silently goes wrong).
 *
 * Re-run this whenever the circuit OR the trusted setup changes -- the emitted fixture is only
 * valid against the exact judges_membership_final.zkey it was generated from.
 */
import path from "node:path";
import { writeFileSync } from "node:fs";
import * as snarkjs from "snarkjs";
import { deriveCredentialSecret, deriveMembershipWitness } from "@judges/crypto";

const BUILD_DIR = path.join(import.meta.dirname, "..", "build");
const WASM = path.join(BUILD_DIR, "judges_membership_js", "judges_membership.wasm");
const ZKEY = path.join(BUILD_DIR, "judges_membership_final.zkey");
const OUT_FILE = path.join(import.meta.dirname, "..", "..", "contracts", "test", "JudgesVerifier.t.sol");

function toInput(witness: ReturnType<typeof deriveMembershipWitness>): Record<string, string> {
  return Object.fromEntries(Object.entries(witness).map(([k, v]) => [k, v.toString()]));
}

function solUintArray(values: string[]): string {
  return `[${values.map((v) => `uint256(${v})`).join(", ")}]`;
}

async function main() {
  const domainSecret = "verifier-fixture-domain-secret";
  const credentialPublicKey = "verifier-fixture-pubkey";
  const applicationId = "judges-demo";
  const policyHash = 7n;

  const credentialSecret = deriveCredentialSecret({
    domainSecret,
    credentialId: "verifier-fixture-cred",
    credentialPublicKey,
  });
  const witness = deriveMembershipWitness({ credentialSecret, credentialPublicKey, applicationId, policyHash });
  const input = toInput(witness);

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, WASM, ZKEY);

  const callData = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  // exportSolidityCallData returns: pA,pB,pC,pubSignals as a comma-joined set of JSON arrays.
  const parsed = JSON.parse(`[${callData}]`) as [string[], string[][], string[], string[]];
  const [pA, pB, pC] = parsed;

  const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership.circom or the trusted setup
// (prover/build/judges_membership_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;

    // A real Groth16 proof for a real membership witness, generated by
    // prover/scripts/export_verifier_fixture.ts -- see that script for how the underlying
    // credentialSecret/commitment/nullifier were derived.
    uint256[2] pA = ${solUintArray(pA)};
    uint256[2][2] pB = [${solUintArray(pB[0])}, ${solUintArray(pB[1])}];
    uint256[2] pC = ${solUintArray(pC)};

    bytes32 constant WALLET_COMMITMENT = bytes32(uint256(${witness.walletCommitment}));
    bytes32 constant NULLIFIER = bytes32(uint256(${witness.nullifier}));
    bytes32 constant DOMAIN = bytes32(uint256(${witness.applicationIdHash}));
    bytes32 constant POLICY_HASH = bytes32(uint256(${witness.policyHash}));

    address wallet = address(0xBEEF);

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        judgesVerifier = new JudgesVerifier(address(zkVerifier), address(nullifierRegistry));
        nullifierRegistry.setVerifier(address(judgesVerifier));
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_TamperedWalletCommitmentRejected() public {
        bytes32 wrongCommitment = bytes32(uint256(WALLET_COMMITMENT) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), wrongCommitment, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_TamperedPolicyHashRejected() public {
        bytes32 wrongPolicy = bytes32(uint256(POLICY_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, wrongPolicy, wallet);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, wrongDomain, NULLIFIER, POLICY_HASH, wallet);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", WALLET_COMMITMENT, DOMAIN, NULLIFIER, POLICY_HASH, wallet);
    }
}
`;

  writeFileSync(OUT_FILE, sol);
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
