/**
 * Emits contracts/test/JudgesField.t.sol: the cross-language check that Solidity's JudgesField
 * library agrees with packages/crypto on concrete values.
 *
 * These two halves must agree exactly or nothing works: the deploy script derives each demo
 * contract's `domain` with the Solidity version, while the prover derives the circuit's
 * `applicationIdHash` public input with the TS version. A mismatch means every proof fails
 * verification on-chain, with no clue pointing at the hash function.
 *
 * Fast (no proving) — safe to re-run any time. Sibling of export_verifier_fixture.ts, which
 * needs the trusted setup and takes minutes.
 */
import path from "node:path";
import { writeFileSync } from "node:fs";
import { assuranceContextHash, derivePolicyHashFromHex, hashToField } from "@judges/crypto";

const OUT_FILE = path.join(import.meta.dirname, "..", "..", "contracts", "test", "JudgesField.t.sol");

/** The app-id strings the three demo contracts are deployed with. */
const APP_IDS = ["judges-dao", "judges-agent-registry", "judges-faucet", "judges-demo"];

const POLICY_CASES = [
  { assurance: "user_verified", wallet: "0x000000000000000000000000000000000000beef" },
  { assurance: "possession", wallet: "0x1111111111111111111111111111111111111111" },
];

function toHex32(bytes: Uint8Array): string {
  return `0x${Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")}`;
}

function domainAssertions(): string {
  return APP_IDS.map(
    (appId) =>
      `        assertEq(JudgesField.hashToField("${appId}"), ${hashToField(appId)}, "${appId}");`,
  ).join("\n");
}

function policyAssertions(): string {
  return POLICY_CASES.map(({ assurance, wallet }, index) => {
    const contextHash = toHex32(assuranceContextHash(assurance));
    const expected = derivePolicyHashFromHex({ contextHash, wallet });
    return `        // case ${index}: assurance "${assurance}"
        assertEq(
            JudgesField.policyHash(${contextHash}, address(uint160(${BigInt(wallet)}))),
            ${expected},
            "${assurance}"
        );`;
  }).join("\n");
}

const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_domain_fixture.ts -- do not hand-edit.
// Re-run that script if packages/crypto's field/policy derivation ever changes.

import {Test} from "forge-std/Test.sol";
import {JudgesField} from "../src/libraries/JudgesField.sol";

/// @notice Pins Solidity's JudgesField against values computed by packages/crypto.
/// @dev These are the two halves of every proof: the prover reduces the app id and the
///      wallet/action binding into BN254's scalar field in TypeScript, and the contracts redo it
///      in Solidity. If they disagree, proofs simply stop verifying on-chain and nothing points
///      at the hash function -- so the agreement is pinned here rather than discovered at deploy
///      time.
contract JudgesFieldTest is Test {
    function test_HashToFieldMatchesOffchain() public pure {
${domainAssertions()}
    }

    function test_PolicyHashMatchesOffchain() public pure {
${policyAssertions()}
    }

    function test_FieldPrimeMatchesBn254ScalarField() public pure {
        assertEq(
            JudgesField.FIELD_PRIME,
            21888242871839275222246405745257275088548364400416034343698204186575808495617
        );
    }
}
`;

writeFileSync(OUT_FILE, sol);
console.log(`Wrote ${OUT_FILE}`);
