/**
 * Emits contracts/test/WebAuthnOnchainSpike.t.sol — a realistic WebAuthn assertion (real P-256
 * keypair, really signed, realistic authenticatorData and clientDataJSON) so the on-chain
 * verification cost can be measured against representative calldata rather than a toy input.
 *
 * Measurement spike for the "put P256VERIFY on JudgesVerifier.verify()'s path" question. Fast,
 * no trusted setup involved.
 */
import path from "node:path";
import { createHash, createSign, generateKeyPairSync, createVerify, sign as cryptoSign, verify as cryptoVerify } from "node:crypto";
import { writeFileSync } from "node:fs";

const OUT_FILE = path.join(import.meta.dirname, "..", "..", "contracts", "test", "WebAuthnOnchainSpike.t.sol");

const RP_ID = "judges.vercel.app";
const ORIGIN = `https://${RP_ID}`;

function b64url(buf: Buffer): string {
  return buf.toString("base64url");
}

function hex(buf: Buffer): string {
  return `0x${buf.toString("hex")}`;
}

function solBytes(buf: Buffer): string {
  return `hex"${buf.toString("hex")}"`;
}

function main() {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });

  // --- authenticatorData: rpIdHash(32) ‖ flags(1) ‖ signCount(4) = 37 bytes, the minimum a
  // --- platform authenticator emits for an assertion (no attested credential data, no
  // --- extensions).
  const rpIdHash = createHash("sha256").update(RP_ID).digest();
  const flags = Buffer.from([0x05]); // user present | user verified
  const signCount = Buffer.from([0x00, 0x00, 0x00, 0x2a]);
  const authenticatorData = Buffer.concat([rpIdHash, flags, signCount]);

  // --- clientDataJSON: the shape browsers actually produce.
  const challenge = createHash("sha256").update("judges-onchain-webauthn-spike").digest(); // 32 bytes
  const clientDataJSON = Buffer.from(
    JSON.stringify({
      type: "webauthn.get",
      challenge: b64url(challenge),
      origin: ORIGIN,
      crossOrigin: false,
    }),
    "utf8",
  );

  // WebAuthn signs sha256(authenticatorData ‖ sha256(clientDataJSON)).
  const clientDataHash = createHash("sha256").update(clientDataJSON).digest();
  const signedPayload = Buffer.concat([authenticatorData, clientDataHash]);
  const messageHash = createHash("sha256").update(signedPayload).digest();

  const signature = cryptoSign("sha256", signedPayload, { key: privateKey, dsaEncoding: "ieee-p1363" });
  if (signature.length !== 64) throw new Error(`unexpected signature length ${signature.length}`);
  const r = signature.subarray(0, 32);
  const s = signature.subarray(32, 64);

  const jwk = publicKey.export({ format: "jwk" }) as { x: string; y: string };
  const qx = Buffer.from(jwk.x, "base64url");
  const qy = Buffer.from(jwk.y, "base64url");

  for (const [name, buf] of [["r", r], ["s", s], ["qx", qx], ["qy", qy], ["messageHash", messageHash]] as const) {
    if (buf.length !== 32) throw new Error(`${name} is ${buf.length} bytes, expected 32`);
  }

  if (!cryptoVerify("sha256", signedPayload, { key: publicKey, dsaEncoding: "ieee-p1363" }, signature)) {
    throw new Error("locally generated signature does not verify — refusing to emit fixture");
  }

  // Byte offsets of the two fields the contract must locate inside clientDataJSON.
  const jsonStr = clientDataJSON.toString("utf8");
  const typeIndex = jsonStr.indexOf('"type":"webauthn.get"');
  const challengeIndex = jsonStr.indexOf('"challenge":"');
  if (typeIndex < 0 || challengeIndex < 0) throw new Error("could not locate clientDataJSON fields");

  const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_webauthn_spike_fixture.ts -- do not hand-edit.

import {Test, console} from "forge-std/Test.sol";
import {WebAuthnOnchainSpike} from "../experiments/WebAuthnOnchainSpike.sol";

/// @notice Measures what on-chain WebAuthn verification would cost, using a real assertion.
/// @dev Monad's P256VERIFY precompile doesn't exist in Foundry's local EVM (the Phase 3
///      finding), so 0x100 is mocked here to return 1. That means the measured number covers
///      EVERYTHING EXCEPT the precompile itself: calldata, the rpIdHash/flag checks, base64url
///      encoding the challenge, the two sha256 calls, and the string comparisons. Monad's
///      documented 6,900 gas for P256VERIFY is added on top when reporting.
contract WebAuthnOnchainSpikeTest is Test {
    WebAuthnOnchainSpike spike;

    bytes constant AUTHENTICATOR_DATA = ${solBytes(authenticatorData)};
    bytes constant CLIENT_DATA_JSON = ${solBytes(clientDataJSON)};
    uint256 constant TYPE_INDEX = ${typeIndex};
    uint256 constant CHALLENGE_INDEX = ${challengeIndex};
    bytes32 constant EXPECTED_RP_ID_HASH = ${hex(rpIdHash)};
    bytes32 constant EXPECTED_CHALLENGE = ${hex(challenge)};
    bytes32 constant R = ${hex(r)};
    bytes32 constant S = ${hex(s)};
    bytes32 constant QX = ${hex(qx)};
    bytes32 constant QY = ${hex(qy)};

    /// @dev Documented Monad cost, from https://docs.monad.xyz/developer-essentials/precompiles
    uint256 constant MONAD_P256VERIFY_GAS = 6_900;

    function setUp() public {
        spike = new WebAuthnOnchainSpike();
        // Mock P256VERIFY: returns 32 bytes of 1, like the real precompile does for a valid
        // signature. Costs ~a few hundred gas instead of the real 6,900, which is corrected for
        // in the reported totals.
        // PUSH1 1, PUSH1 0, MSTORE, PUSH1 0x20, PUSH1 0, RETURN -- returns 32 bytes of value 1.
        vm.etch(address(0x100), hex"600160005260206000f3");
    }

    function _assertion() internal pure returns (WebAuthnOnchainSpike.Assertion memory) {
        return WebAuthnOnchainSpike.Assertion({
            authenticatorData: AUTHENTICATOR_DATA,
            clientDataJSON: CLIENT_DATA_JSON,
            typeIndex: TYPE_INDEX,
            challengeIndex: CHALLENGE_INDEX,
            r: R,
            s: S,
            qx: QX,
            qy: QY
        });
    }

    function _call() internal view returns (bool) {
        return spike.verifyAssertion(_assertion(), EXPECTED_RP_ID_HASH, EXPECTED_CHALLENGE);
    }

    function test_AssertionVerifies() public view {
        assertTrue(_call(), "real assertion should verify with a passing precompile mock");
    }

    function test_WrongChallengeRejected() public view {
        bool ok =
            spike.verifyAssertion(_assertion(), EXPECTED_RP_ID_HASH, bytes32(uint256(EXPECTED_CHALLENGE) ^ 1));
        assertFalse(ok, "an assertion for a different challenge must not verify");
    }

    function test_WrongRpIdRejected() public view {
        bool ok =
            spike.verifyAssertion(_assertion(), bytes32(uint256(EXPECTED_RP_ID_HASH) ^ 1), EXPECTED_CHALLENGE);
        assertFalse(ok, "an assertion for another relying party must not verify");
    }

    function test_MeasureGas() public view {
        uint256 before = gasleft();
        bool ok = _call();
        uint256 used = before - gasleft();
        assertTrue(ok);

        console.log("--- on-chain WebAuthn verification, measured ---");
        console.log("authenticatorData bytes", AUTHENTICATOR_DATA.length);
        console.log("clientDataJSON bytes   ", CLIENT_DATA_JSON.length);
        console.log("EVM execution (precompile mocked, excl. tx calldata)", used);
        console.log("plus real P256VERIFY on Monad", MONAD_P256VERIFY_GAS);
        console.log("subtotal", used + MONAD_P256VERIFY_GAS);
    }
}
`;

  writeFileSync(OUT_FILE, sol);
  console.log(`Wrote ${OUT_FILE}`);
  console.log(`authenticatorData: ${authenticatorData.length} bytes, clientDataJSON: ${clientDataJSON.length} bytes`);
}

main();
