/**
 * Generates a real Groth16 proof against a real membership witness, then emits a Foundry test
 * file exercising the deployed JudgesGroth16Verifier + JudgesVerifier with it directly -- no
 * manual transcription of proof/public-signal values (same reasoning as the P256 test vector in
 * contracts/test/MonadP256Adapter.t.sol: hand-copying long hex/decimal numbers is exactly the
 * kind of thing that silently goes wrong).
 *
 * Also emits a cross-language check: TS's derivePolicyHash vs Solidity's policyHashFor. Those
 * two must agree byte-for-byte or every proof fails verification on-chain, and a mismatch would
 * otherwise only show up at deploy time.
 *
 * Re-run this whenever the circuit OR the trusted setup changes -- the emitted fixture is only
 * valid against the exact judges_membership_final.zkey it was generated from.
 */
import path from "node:path";
import { writeFileSync } from "node:fs";
import * as snarkjs from "snarkjs";
import {
  assuranceContextHash,
  deriveCredentialSecret,
  deriveMembershipWitness,
  derivePolicyHashFromHex,
} from "@judges/crypto";

const BUILD_DIR = path.join(import.meta.dirname, "..", "build");
const WASM = path.join(BUILD_DIR, "judges_membership_js", "judges_membership.wasm");
const ZKEY = path.join(BUILD_DIR, "judges_membership_final.zkey");
const OUT_FILE = path.join(import.meta.dirname, "..", "..", "contracts", "test", "JudgesVerifier.t.sol");

/** 20-byte test address. Kept lowercase: derivePolicyHash hashes raw bytes, not display case. */
const WALLET = "0x000000000000000000000000000000000000beef";

function toInput(witness: ReturnType<typeof deriveMembershipWitness>): Record<string, string> {
  return Object.fromEntries(Object.entries(witness).map(([k, v]) => [k, v.toString()]));
}

function solUintArray(values: string[]): string {
  return `[${values.map((v) => `uint256(${v})`).join(", ")}]`;
}

function toHex32(bytes: Uint8Array): string {
  return `0x${Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")}`;
}

async function main() {
  const domainSecret = "verifier-fixture-domain-secret";
  const credentialPublicKey = "verifier-fixture-pubkey";
  const applicationId = "judges-demo";
  const assurance = "user_verified";

  const contextHash = toHex32(assuranceContextHash(assurance));
  const policyHash = derivePolicyHashFromHex({ contextHash, wallet: WALLET });

  const credentialSecret = deriveCredentialSecret({
    domainSecret,
    credentialId: "verifier-fixture-cred",
    credentialPublicKey,
  });
  const witness = deriveMembershipWitness({ credentialSecret, credentialPublicKey, applicationId, policyHash });
  const input = toInput(witness);

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, WASM, ZKEY);
  const callData = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  const parsed = JSON.parse(`[${callData}]`) as [string[], string[][], string[], string[]];
  const [pA, pB, pC] = parsed;

  const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership.circom or the trusted setup
// (prover/build/judges_membership_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;

    // A real Groth16 proof for a real membership witness, generated by
    // prover/scripts/export_verifier_fixture.ts -- see that script for how the underlying
    // credentialSecret/commitment/nullifier were derived. The proof is bound to WALLET via
    // CONTEXT_HASH, so it only verifies for that exact wallet+action pair.
    uint256[2] pA = ${solUintArray(pA)};
    uint256[2][2] pB = [${solUintArray(pB[0])}, ${solUintArray(pB[1])}];
    uint256[2] pC = ${solUintArray(pC)};

    bytes32 constant WALLET_COMMITMENT = bytes32(uint256(${witness.walletCommitment}));
    bytes32 constant NULLIFIER = bytes32(uint256(${witness.nullifier}));
    bytes32 constant DOMAIN = bytes32(uint256(${witness.applicationIdHash}));
    bytes32 constant CONTEXT_HASH = ${contextHash};
    bytes32 constant EXPECTED_POLICY_HASH = bytes32(uint256(${policyHash}));
    // Emitted as a uint160 cast, not a hex literal: solc rejects non-EIP-55-checksummed address
    // literals, and generating a checksummed string here would just be another thing to get
    // subtly wrong.
    address constant WALLET = address(uint160(${BigInt(WALLET)}));

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        judgesVerifier = new JudgesVerifier(address(zkVerifier), address(nullifierRegistry));
        nullifierRegistry.setVerifier(address(judgesVerifier));
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    /// @dev The cross-language check: Solidity's policyHashFor must equal what TS's
    ///      derivePolicyHash produced when the proof was generated. If these ever diverge,
    ///      every proof silently stops verifying on-chain.
    function test_PolicyHashMatchesOffchainDerivation() public view {
        assertEq(judgesVerifier.policyHashFor(CONTEXT_HASH, WALLET), EXPECTED_POLICY_HASH);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The whole point of the wallet binding: someone lifting this proof out of the mempool
    ///      and submitting it for their own address gets nothing.
    function test_ProofStolenForADifferentWalletRejected() public {
        address attacker = address(0xA11CE);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, attacker);
    }

    /// @dev And the action binding: the same proof can't be redirected to a different action.
    function test_ProofRedirectedToDifferentActionRejected() public {
        bytes32 otherContext = bytes32(uint256(CONTEXT_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, DOMAIN, NULLIFIER, otherContext, WALLET);
    }

    function test_TamperedWalletCommitmentRejected() public {
        bytes32 wrongCommitment = bytes32(uint256(WALLET_COMMITMENT) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), wrongCommitment, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), WALLET_COMMITMENT, wrongDomain, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", WALLET_COMMITMENT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }
}
`;

  writeFileSync(OUT_FILE, sol);
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
