/**
 * Redesign B fixture generator. Produces a real Groth16 proof for a real membership witness
 * against judges_membership_v2, then emits contracts/test/JudgesVerifier.t.sol exercising the
 * deployed JudgesGroth16Verifier + CommitmentTree + JudgesVerifier with it directly — no manual
 * transcription of proof / public-signal values.
 *
 * Re-run this whenever the v2 circuit OR the v2 trusted setup changes — the emitted fixture is
 * only valid against the exact judges_membership_v2_final.zkey it was generated from. It reads
 * the v2 artifacts, so run `pnpm run build:v2 && pnpm run setup:v2` first, and re-export the
 * Solidity verifier (`snarkjs zkey export solidityverifier ...`) so the on-chain VK matches.
 */
import path from "node:path";
import { writeFileSync } from "node:fs";
import * as snarkjs from "snarkjs";
import {
  assuranceContextHash,
  buildIdentityTree,
  deriveIdentityCommitment,
  deriveIdentitySecret,
  deriveMembershipV2WitnessFromTree,
  derivePolicyHashFromHex,
  membershipV2WitnessToInputJson,
} from "@judges/crypto";

const BUILD_DIR = path.join(import.meta.dirname, "..", "build");
const WASM = path.join(BUILD_DIR, "judges_membership_v2_js", "judges_membership_v2.wasm");
const ZKEY = path.join(BUILD_DIR, "judges_membership_v2_final.zkey");
const OUT_FILE = path.join(import.meta.dirname, "..", "..", "contracts", "test", "JudgesVerifier.t.sol");

/** 20-byte test address. Kept lowercase: derivePolicyHash hashes raw bytes, not display case. */
const WALLET = "0x000000000000000000000000000000000000beef";

function solUintArray(values: string[]): string {
  return `[${values.map((v) => `uint256(${v})`).join(", ")}]`;
}

function toHex32(bytes: Uint8Array): `0x${string}` {
  return `0x${Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")}`;
}

async function main() {
  const applicationId = "judges-demo";
  const assurance = "user_verified";

  const contextHash = toHex32(assuranceContextHash(assurance));
  const policyHash = derivePolicyHashFromHex({ contextHash, wallet: WALLET });

  // A small membership set; the fixture proves inclusion of the third identity.
  const secrets = ["11", "22", "33", "44", "55"].map((b) => deriveIdentitySecret(`0x${b.repeat(65)}`));
  const leaves = secrets.map(deriveIdentityCommitment);
  const tree = buildIdentityTree(leaves);

  const witness = deriveMembershipV2WitnessFromTree({ secret: secrets[2], applicationId, tree, policyHash });
  const input = membershipV2WitnessToInputJson(witness);

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, WASM, ZKEY);
  const callData = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  const parsed = JSON.parse(`[${callData}]`) as [string[], string[][], string[], string[]];
  const [pA, pB, pC] = parsed;

  const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// AUTO-GENERATED by prover/scripts/export_verifier_fixture_v2.ts -- do not hand-edit.
// Regenerate whenever prover/circuits/judges_membership_v2.circom or the v2 trusted setup
// (prover/build/judges_membership_v2_final.zkey) changes; this fixture is only valid against the
// exact proving/verifying key pair it was generated from.

import {Test} from "forge-std/Test.sol";
import {JudgesVerifier} from "../src/JudgesVerifier.sol";
import {Groth16Verifier} from "../src/JudgesGroth16Verifier.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";
import {CommitmentTree} from "../src/CommitmentTree.sol";

contract JudgesVerifierTest is Test {
    JudgesVerifier judgesVerifier;
    Groth16Verifier zkVerifier;
    NullifierRegistry nullifierRegistry;
    CommitmentTree commitmentTree;

    // A real Groth16 membership proof (judges_membership_v2), generated by
    // prover/scripts/export_verifier_fixture_v2.ts. The proof is bound to WALLET via CONTEXT_HASH
    // and to the published MERKLE_ROOT.
    uint256[2] pA = ${solUintArray(pA)};
    uint256[2][2] pB = [${solUintArray(pB[0])}, ${solUintArray(pB[1])}];
    uint256[2] pC = ${solUintArray(pC)};

    bytes32 constant MERKLE_ROOT = bytes32(uint256(${witness.merkleRoot}));
    bytes32 constant NULLIFIER = bytes32(uint256(${witness.nullifier}));
    bytes32 constant DOMAIN = bytes32(uint256(${witness.applicationIdHash}));
    bytes32 constant CONTEXT_HASH = ${contextHash};
    bytes32 constant EXPECTED_POLICY_HASH = bytes32(uint256(${policyHash}));
    // Emitted as a uint160 cast, not a hex literal: solc rejects non-EIP-55-checksummed address
    // literals, and generating a checksummed string here would just be another thing to get
    // subtly wrong.
    address constant WALLET = address(uint160(${BigInt(WALLET)}));

    function setUp() public {
        zkVerifier = new Groth16Verifier();
        nullifierRegistry = new NullifierRegistry();
        commitmentTree = new CommitmentTree();
        judgesVerifier =
            new JudgesVerifier(address(zkVerifier), address(nullifierRegistry), address(commitmentTree));
        nullifierRegistry.setVerifier(address(judgesVerifier));
        // Publish the root the proof was generated against; this test contract is the deployer.
        commitmentTree.setRootPoster(address(this));
        commitmentTree.postRoot(MERKLE_ROOT);
    }

    function _proofBytes() internal view returns (bytes memory) {
        return abi.encode(pA, pB, pC);
    }

    /// @dev The cross-language check: Solidity's policyHashFor must equal what TS's
    ///      derivePolicyHash produced when the proof was generated.
    function test_PolicyHashMatchesOffchainDerivation() public view {
        assertEq(judgesVerifier.policyHashFor(CONTEXT_HASH, WALLET), EXPECTED_POLICY_HASH);
    }

    function test_ValidProofVerifiesAndConsumesNullifier() public {
        assertFalse(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
        bool ok = judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        assertTrue(ok);
        assertTrue(judgesVerifier.isNullifierUsed(DOMAIN, NULLIFIER));
    }

    function test_ReplayingSameProofRejectsOnNullifierReuse() public {
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
        vm.expectRevert(
            abi.encodeWithSelector(NullifierRegistry.NullifierAlreadyUsed.selector, DOMAIN, NULLIFIER)
        );
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The membership check: a root the tree never published is rejected before proof verification.
    function test_UnpublishedRootRejected() public {
        bytes32 unknownRoot = bytes32(uint256(MERKLE_ROOT) ^ 1);
        vm.expectRevert(JudgesVerifier.UnknownRoot.selector);
        judgesVerifier.verify(_proofBytes(), unknownRoot, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    /// @dev The wallet binding: someone lifting this proof and submitting it for their own address gets nothing.
    function test_ProofStolenForADifferentWalletRejected() public {
        address attacker = address(0xA11CE);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, attacker);
    }

    /// @dev The action binding: the same proof can't be redirected to a different action.
    function test_ProofRedirectedToDifferentActionRejected() public {
        bytes32 otherContext = bytes32(uint256(CONTEXT_HASH) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, DOMAIN, NULLIFIER, otherContext, WALLET);
    }

    function test_TamperedDomainRejected() public {
        bytes32 wrongDomain = bytes32(uint256(DOMAIN) ^ 1);
        vm.expectRevert(JudgesVerifier.InvalidProof.selector);
        judgesVerifier.verify(_proofBytes(), MERKLE_ROOT, wrongDomain, NULLIFIER, CONTEXT_HASH, WALLET);
    }

    function test_MalformedProofBytesRejected() public {
        vm.expectRevert(JudgesVerifier.MalformedProof.selector);
        judgesVerifier.verify(hex"deadbeef", MERKLE_ROOT, DOMAIN, NULLIFIER, CONTEXT_HASH, WALLET);
    }
}
`;

  writeFileSync(OUT_FILE, sol);
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
